const s = {
  root: {
    // fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    // padding: "24px",
    // maxWidth: 960,
    margin: "0 auto",
  },
  topbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  topbarLeft: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  sectionLabel: {
    // fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.1em",
    // color: "var(--color-text-secondary)",
  },
  countBadge: {
    // fontSize: 11,
    fontWeight: 700,
    background: "var(--color-background-secondary)",
    border: "0.5px solid var(--color-border-secondary)",
    // color: "var(--color-text-secondary)",
    borderRadius: 20,
    padding: "2px 8px",
  },
  btn: {
    fontSize: 13,
    fontWeight: 600,
    padding: "8px 16px",
    background: "var(--color-text-primary)",
    color: "var(--color-background-primary)",
    border: "none",
    borderRadius: "var(--border-radius-md)",
    cursor: "pointer",
  },
  btnMuted: {
    background: "var(--color-background-secondary)",
    color: "var(--color-text-secondary)",
    border: "0.5px solid var(--color-border-secondary)",
  },
  formCard: {
    background: "var(--color-background-primary)",
    border: "0.5px solid var(--color-border-secondary)",
    borderRadius: "var(--border-radius-lg)",
    padding: "24px",
    marginBottom: 20,
  },
  formRow: {
    display: "flex",
    gap: 24,
    alignItems: "flex-start",
  },
  formLeft: {
    flex: 1,
    minWidth: 0,
  },
  vDivider: {
    width: 0.5,
    alignSelf: "stretch",
    background: "var(--color-border-tertiary)",
    flexShrink: 0,
  },
  formRight: {
    width: 200,
    flexShrink: 0,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    color: "var(--color-text-secondary)",
    marginBottom: 8,
    textTransform: "uppercase",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    fontSize: 14,
    border: "0.5px solid var(--color-border-secondary)",
    borderRadius: "var(--border-radius-md)",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "inherit",
    background: "var(--color-background-secondary)",
    color: "var(--color-text-primary)",
  },
  iconRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: "var(--border-radius-md)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "all 0.15s",
  },
  colorGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 6,
  },
  colorSwatch: {
    width: "100%",
    aspectRatio: "1",
    borderRadius: "var(--border-radius-md)",
    cursor: "pointer",
    transition: "all 0.15s",
  },
  previewCard: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: "var(--border-radius-md)",
    border: "0.5px solid",
  },
  previewAvatar: {
    width: 32,
    height: 32,
    borderRadius: "var(--border-radius-md)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    flexShrink: 0,
  },
  previewName: {
    fontSize: 13,
    fontWeight: 600,
    margin: 0,
  },
  previewSub: {
    fontSize: 11,
    margin: 0,
    opacity: 0.6,
  },
  createBtn: {
    width: "100%",
    marginTop: 12,
    padding: "10px",
    background: "var(--color-text-primary)",
    color: "var(--color-background-primary)",
    border: "none",
    borderRadius: "var(--border-radius-md)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "opacity 0.15s",
  },
  grid: {
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
  },
  catCard: {
    position: "relative",
    width: 160,
    borderRadius: "var(--border-radius-lg)",
    border: "0.5px solid",
    padding: "18px 16px 14px",
  },
  newBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    fontSize: 10,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 20,
    letterSpacing: "0.06em",
  },
  catAvatar: {
    width: 48,
    height: 48,
    borderRadius: "var(--border-radius-md)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  catName: {
    fontSize: 14,
    fontWeight: 700,
    margin: "0 0 2px",
    letterSpacing: "-0.2px",
    wordBreak: "break-word",
  },
  catId: {
    fontSize: 11,
    fontWeight: 600,
    margin: "0 0 14px",
    opacity: 0.5,
  },
  catFooter: {
    borderTop: "0.5px solid",
    paddingTop: 10,
  },
  catStat: {
    fontSize: 11,
    fontWeight: 600,
  },
  addCard: {
    width: 160,
    borderRadius: "var(--border-radius-lg)",
    border: "0.5px dashed var(--color-border-secondary)",
    padding: "18px 16px",
    background: "transparent",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    minHeight: 148,
    transition: "background 0.15s",
  },
  addCardPlus: {
    fontSize: 24,
    color: "var(--color-text-tertiary)",
    fontWeight: 300,
    lineHeight: 1,
  },
  addCardText: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--color-text-tertiary)",
    letterSpacing: "0.04em",
  },
  shimmerGrid: {
    display: "flex",
    gap: 12,
  },
  shimmerCard: {
    width: 160,
    height: 148,
    borderRadius: "var(--border-radius-lg)",
    background: "var(--color-background-secondary)",
    border: "0.5px solid var(--color-border-tertiary)",
  },
  emptyWrap: {
    textAlign: "center",
    padding: "48px 24px",
    background: "var(--color-background-secondary)",
    borderRadius: "var(--border-radius-lg)",
    border: "0.5px dashed var(--color-border-secondary)",
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--color-text-primary)",
    margin: "0 0 6px",
  },
  emptySub: {
    fontSize: 13,
    color: "var(--color-text-secondary)",
    margin: "0 0 20px",
  },
};
export default s;